-- Your SQL goes here
CREATE TABLE "users" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" text UNIQUE NOT NULL,
    "email" text UNIQUE NOT NULL,
    "phone" text NOT NULL DEFAULT (''),
    "avatar" text NOT NULL DEFAULT (''),
    "location" text NOT NULL DEFAULT (''),
    "age" integer NOT NULL DEFAULT (0),
    "gender" integer NOT NULL DEFAULT (0),
    "password_hash" text NOT NULL,
    CONSTRAINT "pk_users" PRIMARY KEY ("id")
);

CREATE TABLE "messages" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "from_user" integer NOT NULL,
    "to_user" integer NOT NULL,
    "quote_id" integer NULL DEFAULT (NULL),
    "message" text NOT NULL,
    "message_type" integer NOT NULL,
    "send_time" timestamp without time zone NOT NULL,
    "read_time" timestamp without time zone NULL DEFAULT (NULL),
    CONSTRAINT "pk_messages" PRIMARY KEY ("id"),
    CONSTRAINT "fk_from_user_id" FOREIGN KEY ("from_user") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_to_user_id" FOREIGN KEY ("to_user") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE TABLE "friends" (
    "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer NOT NULL,
    "friend_user_id" integer NOT NULL,
    CONSTRAINT "pk_friends" PRIMARY KEY ("id"),
    CONSTRAINT "fk_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_friend_user_id" FOREIGN KEY ("friend_user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE INDEX "ix_users_id" ON "users" ("id");
CREATE INDEX "ix_messages_id" ON "messages" ("id");
CREATE INDEX "ix_messages_quote_id" ON "messages" ("quote_id");
CREATE INDEX "ix_messages_from_user" ON "messages" ("from_user");
CREATE INDEX "ix_messages_to_user" ON "messages" ("to_user");
CREATE INDEX "ix_friends_id" ON "friends" ("id");
CREATE INDEX "ix_friends_user_id" ON "friends" ("user_id");
CREATE INDEX "ix_friends_friend_user_id" ON "friends" ("friend_user_id");
